app_title: l’Explorateur de valeurs de calcul

dv_dropdown: Valeurs de conception

main_tabs:
  map-tab: Carte
  table-tab: Tableau C-2
  help-tab: Aide
  about-tab: À propos

overlay-options:
  title: Options de superposition
  columns:
    - title: Période
      width: 4
    - title: Réchauffement climatique
      width: 4
    - title: Stations
      width: 2
      label: (HISTORICAL ONLY)
    - title: Grille
      width: 2

show_stations:
  label: (HISTORIQUE SEULEMENT)

colorscale-options:
  title: Options de l'échelle de couleurs
  columns:
    color-map:
      title: Palette de couleurs
      width: 3
    scale:
      title: Échelle
      width: 2
    num-colors:
      title: Nombre de couleurs
      width: 3
    range:
      title: Gamme (loading)
      width: 4
  column-order:
    - color-map
    - scale
    - num-colors
    - range

color_scale_type:
  - value: linear
    label: Linéaire
  - value: logarithmic
    label: Logarithmique

colorscale_options_range:
  label: "Échelle: {min} à {max}"

climate_regime:
  # Labels for the two climate regime selections
  historical:
    short: Historique
    long: Valeurs de conception historiques
  future:
    short: Futur
    long: Changement futur par rapport à 1986-201

historical_dataset:
  model: Model
  reconstruction: Reconstruction

interpolation: Donnée interpolée

future_change_factors:
  short: "{value}{separator}{units}"
  long: "{value}°C par rapport à 1986-2016"

map:
  title:
    historical: "{dv} • {climate_regime}{dataset}"
    future: "{dv} • Variable de niveau {tier}  • {climate_regime}{dataset}"
  no_dvs_for_climate_regime: |
    Aucune valeur {what} n'est disponible pour le variable {dv} pour le moment.
  no_data_error: |
    Error: Les données ne sont pas disponibles pour <br>
    <b>{title}</b> <br><br>
    Veuillez signaler cette erreur au contact de l'application fournit 
    dans l'onglet <b>À propos > Contact</b> tab.
  heatmap_hover_template: |
    <b>{dv_label} interpolé: %{{z}} </b><br>
  station_hover_template: |
    <b>Station {dv_label}: %{{text}}</b><br>

map_pointer_output:
  title: Données du pointeur de la carte
  subtitle: |
    *Passez le pointeur sur la carte pour montrer l'emplacement actuel du pointeur. 
    Cliquez pour conserver les valeurs pour téléchargement.*

download_table:
  dv: Valeur de conception
  units: Unités

table_C2:
  title: |
    Valeur de conception pour {name_and_units} aux emplacements de Tableau C-2. 
    Pour les projections futures, {name} est une variable de niveau {tier}.
  no_table_data_error: |
    Erreur: Aucune donnée n'est disponible pour ce tableau.
    Veuillez signaler cette erreur au contact de l'application fournit 
    dans l'onglet **À propos > Contact** tab.
  no_station_data: "Le variable {} n'a pas de données historiques"

misc:
  location:
    long: Emplacement
    short: Empl
  province:
    long: Province
    short: Prov
  longitude:
    long: Longitude
    short: Lon
  latitude:
    short: Lat
    long: Latitude
  download_data_button_text: Télécharger ces données

dvs:
  DRWP5:
    description: Pression de la pluie chassée par le vent, 1/5
  HDD:
    description: "Degrés-jours de chauffage en dessous de 18 \xB0C"
  IDFCF:
    description: Facteur de changement de l'IDF
  MI:
    description: L’indice d'humidité
  PAnn:
    description: Précipitations totales annuelles
  R15m10:
    description: Pluies sur 15 minutes, 1/10
  R1d50:
    description: Pluies sur 1 jour, 1/50
  RAnn:
    description: Pluies totales annuelles
  RHAnn:
    description: L’humidité relative moyenne annuelle
  RL50:
    description: Charge de pluie sur la neige, 1/50
  SL50:
    description: Charge de neige, 1/50
  TJan1.0:
    description: Température de janvier, 1%
  TJan2.5:
    description: Température de janvier, 2,5%
  TJul97.5:
    description: Température de juillet, 97,5%
  Tmax:
    description: Température journalière maximale annuelle
  Tmin:
    description: Température journalière minimale annuelle
  TwJul97.5:
    description: Température de juillet du thermomètre mouillé, 97,5%
  WP10:
    description: Pressions de vent maximales annuelles, 1/10
  WP50:
    description: Pressions de vent maximales annuelles, 1/50
