version: 1
disable_existing_loggers: True

formatters:
  simple:
    format: '%(asctime)s.%(msecs)03d:%(levelname)s:%(name)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  json:
    format: '%(asctime)s.%(msecs)03d:%(levelname)s:%(name)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
    class: pythonjsonlogger.jsonlogger.JsonFormatter

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stderr
  error:
    class: logging.StreamHandler
    level: ERROR
    formatter: json
    stream: ext://sys.stderr
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: json
    filename: 'dve_log.txt'

loggers:
  dve:
    level: DEBUG
    handlers: [console,file]
    propagate: no

root:
  level: DEBUG
  handlers: [console,file]