# Design variables to actually offer in the UI.
# Simplifies taking them in and out of service.
- DRWP5
- HDD
- IDFCF
#        - MI  # No change factor files
- PAnn
- R1d50
- R15m10
- RAnn
- RL50
- RHann
- SL50
- TJan2.5
- TJan1.0
- TJul97.5
- TwJul97.5
- Tmax
- Tmin
- WP10
- WP50
