# Args controlling initial settings and other features of controls.
# These are dependent on the type of control, e.g., climate-regime is a
# dcc.RadioItems, and that determines the argument names, values, and
# effects. This is not quite as abstract as would be nice, but it does
# move the details of formatting from code to config.
language:
  value: "en"
  style:
    font-size: 0.9rem
main_tabs:
  active_tab: map-tab
help_tabs:
  active_tab: help_tab-0
about_tabs:
  active_tab: about_tab-0
design-value-id:
  value: HDD
  searchable: true
  clearable: false
climate-regime:
  value: historical   # Initial setting
  labelStyle:
    display: block
    font-size: 1.2em
    margin-top: "1em"
historical-dataset:
  value: reconstruction   # Initial setting
  clearable: false
global_warming:
  style:
    font-size: 1.2em
future-dataset:
  value: "0.5"    # Initial setting
  disabled: true
  clearable: false
mask:
  "on": true    # Initial setting
  style:
    width: "50px"
stations:
  "on": false   # Initial setting
  label:
    style:
      font-size: "0.8em"
      font-style: italic
  labelPosition: bottom
  style:
    width: "100px"
grid:
  "on": false   # Initial setting
  style:
    width: "50px"
colour-map:
  value: None   # Immediately overridden
  style:
    font-size: 1.1em
scale:
  value: logarithmic
  clearable: false
  style:
    font-size: 1.1em
num-colours:
  min: 5
  max: 100
  step: 5
  value: 10
  size: 150
  handleLabel:
    showCurrentValue: true
    label: " "
  marks:
    "5": "5"
    "100": "100"
colourbar-range: {}
