|
  The **Map** tab displays the selected design value in the form of a 
  Canada-wide map.
  Here is an explanation of the various controls available to customize 
  the map.

  ## Map display

  **Note**: The underlying projection for the maps is a rotated polar stereographic grid,
  but the appearance of any given map is affected by the browser settings; see below for details. 

  The map display is a Plotly Graph, which comes equipped with tools for zooming, panning,
  and taking a PNG image snapshot of the display. For information on these tools, which appear
  in the "modebar" at the top right of the display, see:

    <a href="https://plotly.com/chart-studio-help/getting-to-know-the-plotly-modebar/" target="_blank">
    An Introduction to Chart Studio Modebar
    </a>.

  In addition to the map itself, the map display contains a title and a colour bar.

  ### Map title

  Includes the design variable, units, and historical/future indicator.

  ### Colour bar

  The colour bar uses the selected colour scale, with annotations showing values
  uniformly spaced over the range. When the number of colours selected is 10 or
  fewer, the annotations are placed at the colour interval boundaries. Otherwise,
  11 annotations are placed uniformly across the range. 

  Hover the pointer over the colour bar to show the midpoint value of the
  interval represented by the colour. This can be useful when the number of
  colours is large and you wish to get an idea of the value represented
  by a particular colour.

  ### Map aspect ratio and zoom capability

  The aspect ratio of the map is affected by the width of the browser window in which
  DVE is running. Therefore, you can adjust the aspect ratio by resizing the browser window
  and/or using your browser's zoom in/out feature (Ctrl+ / Ctrl- keys in Windows,
  Command+ / Command- in MacOS, in Firefox and Chrome browsers).

  The zoom feature is engaged by clicking on the map, dragging a rectangle, and releasing.
  The selected region now fills the entire map display. In some cases, this can result in a
  distorted map appearance, since the original aspect ratio is not maintained. Resizing the
  browser or using its zoom feature, as mentioned above, should improve the appearance. 
  Alternatively, exit zoom mode (by double-clicking on the map) and choose a different rectangle.

  ## Overlay Options

  "Overlay" refers to the various layers comprising the map.

  - A colour map of Canada is always displayed.
  - Station design values (for historical data only) can be overlaid.
  - A longitude-latitude reference grid can be overlaid.

  ### Mapping options

  To display a map of interpolated historical data:

  1. Click the **Historical design values** radio button under **Period** in the **Overlay Options**
     section.
  2. The map displays the selected design value field, along with its units.

  To display a map of future projected changes:

  1. Click the **Future change relative to 1986-2016** radio button under **Period** in the
     **Overlay Options** section.
  2. Select the level of **Global Warming** in the corresponding dropdown menu in the Overlay Options
     section.
  3. The map displays the changes from the reference period at the chosen Global Warming level.
     - For temperature-based variables, changes are additive in units of the original variable.
     - For other variables, changes are multiplicative factors with units indicated as "ratio".

  ### Station locations

  Stations are the fundamental source of data for historical design values.
  To see the stations displayed as circular markers on the map, slide the
  **Stations** switch to the right ("on" position).
  The value of the design variable at the station is indicated using the same
  colour scale as used for the map.

  ### Longitude-latitude grid

  To overlay the longitude-latitude grid, slide the **Grid** switch to the
  right ("on" position). The grid spacing is automatically adjusted in zoom mode.

  ## Colour Scale Options

  The Colour Scale Options control how the map and station data values are displayed.

  - **Colour Palette** determines the fundamental set of
    colours used to build the colour scale.
  - **Scale** determines whether data are mapped to the colour scale
    linearly or logarithmically.
  - **Num. Colours** specifies the number of colours in the colour scale.
  - **Range** determines what range of values are represented as colours.

  ### Colour Palette

  Select the fundamental colour palette. Many colour palette are interpolated 
  between two or three fixed colours, while others are more heterogeneous. 
  Names for interpolated colour palettes usually indicate the colours involved.
  Names ending in "_r" have the same colours as the base colour palette, but in 
  reverse order.

  ### Scale

  Select Linear or Logarithmic mapping of data values to colours. 
  Some selections of **Design Variable**
  and **Period** do not permit logarithmic scales; in this case the
  selector is disabled and the scale is fixed to linear. The 
  data intervals in the colour scale are uniformly spaced (linearly or 
  logarithmically)
  over the range. Finally, for design value fields with minima near zero, the
  minimum value is adjusted to a fixed fraction (typically 1/100) of the 
  maximum value.

  ### Num. Colours

  Select the number of colours in the scale by dragging the
  pointer. A small number of colours gives a contour effect,
  which can be useful to identify particular values of interest.
  A larger number of colours gives a continuous gradient effect.

  ### Range

  Select the range of data values to be coloured. 
  Data values below/above the field minimum/maximum are represented as the
  lowest/highest value colour. Missing data values are represented as transparent,
  which means that the map background colour shows through. The maximum range is
  fixed by the field values, but the user can narrow this range if desired.

  ## Extracting data from the map display

  The map display is interactive and provides detailed information about the
  values when the pointer is hovered or clicked on the map. This information
  can be downloaded as a CSV file.

  ### Hover: Single design value and location

  When you hover the pointer over the map:

  - a popup displays the design value at the current pointer location.
  - a table in the **Data from map pointer** area displays the
    latitude and longitude of the current pointer location. These values update
    continuously as the pointer is moved, unless there is no data under the pointer.

  ### Click: All design values and location

  When you click the pointer on the map, two tables in the
  **Data from map pointer** area show:

  - the location of the cell on which you clicked.
  - the values of all Design Variables at that location. 

  Values are updated only when you click on a cell.

  **Note**: The **Data from map pointer** table shows a lot of information, and its text may 
  appear too small. To enlarge the text, you can use your browser's Zoom In/Out feature
  (Ctrl+ / Ctrl- keys in Windows, Command+ / Command- in MacOS, in Firefox and Chrome
  browsers) to adjust the text size.

  ### Downloading click data

  When you have clicked on a cell to display the location and design values, you can download
  this information as a (single) CSV file by clicking the **Download this data** button.

  ### Output to PNG

  Click on the camera icon in the modebar to download the displayed map as a PNG file. Note
  that the output reflects exactly what appears on the screen, including the overlays, size
  and aspect ratio. The latter can be adjusted using your browser's Zoom In/Out feature
  (Ctrl+ / Ctrl- keys in Windows, Command+ / Command- in MacOS, in Firefox and Chrome browsers).
