version: '2.3'
services:
  dv-explorer-prod:
    image: pcic/dash-dv-explorer
    container_name: design-value-explorer
    env_file:
      - env.env
    ports:
      - "30020:5000"
    volumes:
      # Gunicorn
      - type: bind
        source: ./gunicorn.conf
        target: /app/docker/production/gunicorn.conf
        read_only: true
      - type: bind
        source: ./gunicorn-logging.conf
        target: /app/docker/production/gunicorn-logging.conf
        read_only: true

      # App logging
      - type: bind
        source: ../../app-logging.yml
        target: /app/app-logging.yml
        read_only: true

      # App configuration
      - type: bind
        source: ./app-config.yml
        target: /app/app-config.yml
        read_only: true
      - type: bind
        source: ../../config/
        target: /app/config/
        read_only: true

        # Data files
      - type: bind
        source: /storage/data/projects/comp_support/dv-explorer/data/model_inputs/
        target: /app/dve/data/model_inputs/
        read_only: true
      - type: bind
        source:  /storage/data/projects/comp_support/dv-explorer/data/reconstructions/
        target: /app/dve/data/reconstructions/
        read_only: true
      - type: bind
        source: /storage/data/projects/comp_support/dv-explorer/data/station_inputs/
        target: /app/dve/data/station_inputs/
        read_only: true
      - type: bind
        source:  /storage/data/projects/comp_support/dv-explorer/data/tables_2022_02/
        target: /app/dve/data/tables/
        read_only: true
      - type: bind
        source: /storage/data/projects/nrc/CanRCM4_large_ensemble/design_values/change_factors/
        target: /app/dve/data/change_factors/
        read_only: true

        # Download files: presently are permanent so best stored in an
        # external mount where old ones can be deleted periodically.
        # TODO: Remove after upgrading to use temporary files
      - type: bind
        source: ./downloads
        target: /downloads

    tmpfs:
      - /downloads/by-location:size=200M,uid=1000

    mem_limit: 8g
    memswap_limit: 8g
    restart: "unless-stopped"

networks:
  default:
    external:
      name: pcicbr0
