version: '3.2'
services:
  dv-explorer-prod:
    build:
      context: ../..
      dockerfile: ./docker/production/Dockerfile
    image: pcic/dash-dv-explorer
    container_name: dv-explorer-prod
    env_file:
      - .env
    ports:
      - "30020:5000"
    volumes:
      # Gunicorn
      - type: bind
        source: ./gunicorn.conf
        target: /app/docker/production/gunicorn.conf
        read_only: true
      - type: bind
        source: ./gunicorn-logging.conf
        target: /app/docker/production/gunicorn-logging.conf
        read_only: true

      # App logging
      - type: bind
        source: ../../app-logging.yml
        target: /opt/dockremap/app-logging.yml
        read_only: true
      - type: bind
        source: ../../dve_log.txt
        target: /opt/dockremap/dve_log.txt

      # App configuration
      - type: bind
        source: ./app-config.yml
        target: /opt/dockremap/app-config.yml
        read_only: true
      - type: bind
        source: ../../config/
        target: /opt/dockremap/config/
        read_only: true

        # Data files
      - type: bind
        source: /storage/data/projects/comp_support/dv-explorer/data/model_inputs/
        target: /app/dve/data/model_inputs/
        read_only: true
      - type: bind
        source: ../../local-data/reconstructions/
#        source: /storage/data/projects/comp_support/dv-explorer/data/reconstructions/
        target: /app/dve/data/reconstructions/
        read_only: true
      - type: bind
        source: /storage/data/projects/comp_support/dv-explorer/data/station_inputs/
        target: /app/dve/data/station_inputs/
        read_only: true
      - type: bind
        source: ../../local-data/tables/
#        source: /storage/data/projects/comp_support/dv-explorer/data/tables_2022_02/
        target: /app/dve/data/tables/
        read_only: true
      - type: bind
        source: ../../local-data/change_factors/
#        source: /storage/data/projects/nrc/CanRCM4_large_ensemble/design_values/change_factors/
        target: /app/dve/data/change_factors/
        read_only: true

        # Download files: presently are permanent so best stored in an
        # external mount where old ones can be deleted periodically.
        # TODO: Remove after upgrading to use temporary files
      - type: bind
        source: ./downloads
        target: /downloads

#networks:
#  default:
#    external:
#      name: pcicbr0
