version: 15
path_separator: ";"
function_prefix: "@"
ui_elements:
  - id: main_tabs
    prop: active_tab
    global: ui;controls;main_tabs;active_tab
  - id: help_tabs
    prop: active_tab
    global: ui;controls;help_tabs;active_tab
  - id: about_tabs
    prop: active_tab
    global: ui;controls;about_tabs;active_tab
  - id: show_stations
    prop: "on"
    global: "@show_stations"
    local: ui;controls;stations;{climate_regime};on
  - id: show_grid
    prop: "on"
    global: ui;controls;grid;on
  - id: num_colors
    prop: value
    global: ui;controls;num-colours;value
    local: dvs;{design_variable};{climate_regime};num_colours
  - id: color_map
    prop: value
    global: dvs;{design_variable};{climate_regime};colour_map
  - id: color_scale_type
    prop: value
    global: dvs;{design_variable};{climate_regime};scale;default
