# For documentation of this config, see dve/callbacks/local_preferences.py

version: 17
path_separator: ";"
function_marker: "@"
ui_elements:
  # Adding this local pref causes the double-update problem to occur.
  # This is diagnostic, of course, but no time to pursue it. TODO.
  # - selector: design_variable.value
  #    paths:
  #      global: ui;controls;design-value-id;value

  - selector: main_tabs.active_tab
    paths:
      global: ui;controls;main_tabs;active_tab

  - selector: help_tabs.active_tab
    paths:
      global: ui;controls;help_tabs;active_tab

  - selector: about_tabs.active_tab
    paths:
      global: ui;controls;about_tabs;active_tab

  - selector: show_stations.on
    inputs:
      climate_regime: climate_regime.value
    paths:
      global: "@show_stations"
      local: ui;controls;stations;{climate_regime};on

  - selector: show_grid.on
    paths:
      global: ui;controls;grid;on

  - selector: num_colors.value
    inputs:
      design_variable: design_variable.value
      climate_regime: climate_regime.value
    paths:
      global: ui;controls;num-colours;value
      local: dvs;{design_variable};{climate_regime};num_colours

  - selector: color_map.value
    inputs:
      design_variable: design_variable.value
      climate_regime: climate_regime.value
    paths:
      global: dvs;{design_variable};{climate_regime};colour_map

  - selector: color_scale_type.value
    inputs:
      design_variable: design_variable.value
      climate_regime: climate_regime.value
    paths:
      global: dvs;{design_variable};{climate_regime};scale;default
