|
  The Help tab contains information on how to use the application's user
  interface. For information on interpreting values and on the science and
  methods behind the data presented in Design Value Explorer, see XXX.

  ## Overview

  Design Value Explorer (DVE) enables enables users to access historical
  design variables across Canada, in either map or table form, examine
  projected future change in design variables, and download maps and tables.

  - For the historical period, there are both observations (station data at
    specific locations) and interpolated rasters covering all of Canada.

  - For future periods, projections are rasters covering most of Canada. Each
    future projection is characterized by a global warming level
    in °C above baseline (e.g., 2.0 °C).

  ## Main tabs

  DVE presents the design data in two ways: As maps and in tabular format,
  under the **Map** and **Table C-2** tabs respectively.

  - The Map tab shows the interpolated rasters (historical or future), with the
    option of overlaying station observations for the historical period.

  - The Table C-2 tab presents both historical and future projected design values
    at a set of standard locations compiled in the National Building Code of
    Canada.

  The **Help** and **About** tabs contain supplementary information
  about DVE.

  ## Design Variable selection

  For both tabs, DVE displays data for one design variable at a time, which is
  selected from the Design Variable drop-down menu.

  ## Local storage of your preferences

  DVE "remembers" the value of various options you select. In this way,
  it builds up a local database of your preferences for viewing the data.
  (This preference information is stored locally in your browser. There is
  no way for DVE to know who you are apart from the browser you are using.)

  For example, when you select a Colour Map for
  a map display, DVE stores that selection in association with the currently
  selected Design Variable and Period. Whenever you select that particular
  combination of DV and Period again, the stored Colour Map for that
  combination is set.

  All options start out with default settings. As you use the app,
  default settings are replaced by your preferences.

  Preference storage persists between sessions with DVE, so your preferences
  persist even if you close the DVE browser window or refresh the page.

  The following options are managed as preferences:

  | Tab | Option | Associated with |
  | ----- | --- | --- |
  | -     | Main tab selection | - |
  | Map   | Period | - |
  | Map   | Global Warming | - |
  | Map   | Stations | - |
  | Map   | Grid | - |
  | Map   | Colour Map | Design Variable; Period |
  | Map   | Scale | Design Variable; Period |
  | Map   | Num. Colours | Design Variable; Period |
  | Help  | Secondary tab selection | - |
  | About | Secondary tab selection | - |

  Note: The associations for each option (particularly Map options) have
  been selected with with maximum utility for viewing the data in mind.