|
  Design values are provided at locations specified by geographic location in
  the National Building Code of Canada (NBCC) Table C-2 and gathered by province.
  The  **NBCC** column gives the value from the most recent edition of the Code
  (current up to 2020), the **PCIC** column gives the value extracted from the DVE
  map for the historical reference period (1986-2016); and the remaining columns
  contain the change factors (CF), relative to the reference period, at the
  specified levels of global warming.

  - For temperature-based variables, the change factors are additive and
    in units of the original variable.
  - For all other variables, the change factors are multiplicative and
    hence unitless. This includes the change factor for IDF curves, IDFCF,
    which should be applied across all durations.

  Also note that in this version of DVE:

  - The design variables RHAnn, Tmax and Tmin are not part of the NBCC,
    but are provided in the Canadian Highway Bridge Design Code.
  - Future change factors for the Moisture Index, MI, are not available at
    this time.
