|
  Design values are provided at locations specified by geographic location in
  the NBCC Table C-2 and gathered by province. The  **NBCC** column gives the
  value from the most recent edition of the Code (current up to 2020),
  the **PCIC** column gives the value extracted from the DVE map for the
  historical reference period (1986-2016); and the remaining columns contain
  the change factors (CF), relative to the reference period, at the specified
  levels of global warming.

  - For temperature-based variables, the change factors are additive and
    in units of the original variable.
  - For all other variables, the change factors are multiplicative and
    hence unitless.

  There are some gaps in the Tables in this version of DVE:

  - Future change factors for MI are not available at this time.
  - Design variables IDFCF, RHAnn, Tmax and Tmin are not part of the NBCC,
    but were produced for the DVE.