label: Team
cards:
  - header: "[Charles Curry](https://www.uvic.ca/pcic/about/our-people/profiles/curry-charles.php)"
    body: Climate science lead.
  - header: "[James Hiebert](https://www.uvic.ca/pcic/about/our-people/profiles/hiebert-james.php)"
    body: Development team lead.
  - header: "Rod Glover"
    body: Frontend development lead.
  - header: "[Tom Kunkel](https://www.uvic.ca/pcic/about/our-people/profiles/kunkel-tom.php)"
    body: System administration.
  - header: Nic Annau
    body: |
      Developer of hybrid spatial mapping software and initial version 
      of DVE.