tabs:
  en:
    - label: Introduction
      content: !include config/text/help/en/intro.yml
    - label: Map tab
      content: !include config/text/help/en/map.yml
    - label: Table C-2 tab
      content: !include config/text/help/en/table_C2.yml
  fr:
    - label: Introduction
      content: !include config/text/help/fr/intro.yml
    - label: Map tab
      content: !include config/text/help/fr/map.yml
    - label: Table C-2 tab
      content: !include config/text/help/fr/table_C2.yml
