tabs:
  en:
    - label: Introduction
      content: !include config/text/help/intro.yml
    - label: Map tab
      content: !include config/text/help/map.yml
    - label: Table C-2 tab
      content: !include config/text/help/table_C2.yml
