label: Équipe
cards:
  - header: "[Charles Curry](https://www.uvic.ca/pcic/about/our-people/profiles/curry-charles.php)"
    body: Responsable de la science du climat.
  - header: "[James Hiebert](https://www.uvic.ca/pcic/about/our-people/profiles/hiebert-james.php)"
    body: Responsable de l'équipe de développement.
  - header: "Rod Glover"
    body: Responsable du développement du front-end.
  - header: "[Tom Kunkel](https://www.uvic.ca/pcic/about/our-people/profiles/kunkel-tom.php)"
    body: Administrateur du système.
  - header: Nic Annau
    body: |
      Développeur d'un logiciel de hybride cartographie spatiale et de la 
      version initiale de DVE.
  - header: "Dhouha Ouali"
    body: Aide à la traduction française.