name: Python CI

on: push

jobs:
  test:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install git libgeos-dev

    - name: Install pipenv
      run: |
        pip install -U pipenv

    - id: cache-pipenv
      uses: actions/cache@v4.2.0
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

    - name: Install dependencies if changed
      if: steps.cache-pipenv.outputs.cache-hit != 'true' && ${{ matrix.python-version == '3.8' }}
      run: |
        pipenv install --dev
        pipenv run pip install .

# We aren't using a matrix testing strategy yet
#    - name: Re-install dependencies if alternative python version
#      if: ${{ matrix.python-version != '3.8' }}
#      run: |
#        mv Pipfile.lock do-not-use
#        pipenv install --python ${{ matrix.python-version }} --dev

    - name: Test with pytest
      run: |
        pipenv run pytest -v --tb=short tests/
